services:

  db:
    image: postgres:16-alpine
    container_name: tcc-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sistema-os

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 12


  api:
    build:
      context: ./backend

    container_name: tcc-api

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8080:8080"

    volumes:
      - ./backend/.env:/app/.env

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: sistema-os


  app:
    build:
      context: ./frontend

    container_name: tcc-app

    depends_on:
      - api

    ports:
      - "5173:5173"


volumes:
  pgdata: